apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "karpetrack.fullname" . }}
  labels:
    {{- include "karpetrack.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: [pods]
    verbs: [get, list, watch]
  - apiGroups: [""]
    resources: [nodes]
    verbs: [get, list, watch, create, delete, patch, update]
  - apiGroups: [""]
    resources: [events]
    verbs: [create, patch]
  - apiGroups: [karpetrack.io]
    resources: [spotnodes, spotnodepools]
    verbs: [get, list, watch, create, update, patch, delete]
  - apiGroups: [karpetrack.io]
    resources: [spotnodes/status, spotnodepools/status]
    verbs: [get, update, patch]
  - apiGroups: [coordination.k8s.io]
    resources: [leases]
    verbs: [get, list, watch, create, update, patch, delete]
