{{- if .Values.credentials.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "karpetrack.secretName" . }}
  labels:
    {{- include "karpetrack.labels" . | nindent 4 }}
type: Opaque
stringData:
  refresh-token: {{ .Values.credentials.refreshToken | quote }}
  cloudspace-id: {{ .Values.credentials.cloudspaceId | quote }}
{{- end }}
