{{- if .Values.credentials.create -}}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace (include "karpetrack.secretName" .) -}}
{{- if or (not $existingSecret) (and .Values.credentials.refreshToken .Values.credentials.cloudspaceId) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "karpetrack.secretName" . }}
  labels:
    {{- include "karpetrack.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
stringData:
  refresh-token: {{ .Values.credentials.refreshToken | quote }}
  cloudspace-id: {{ .Values.credentials.cloudspaceId | quote }}
{{- end }}
{{- end }}
