apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: karpetrack-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: karpetrack-controller
subjects:
  - kind: ServiceAccount
    name: karpetrack-controller
    namespace: karpetrack-system
